[bot]
plugin_dirs = ["plugins"]
adapters = ["iamai.adapter.cqhttp"]

[bot.log]
level = "INFO"
verbose_exception = true

[adapter.cqhttp]
adapter_type = "ws-reverse"
host = "0.0.0.0"
port = 3001
url = "/cqhttp/ws"